services:
  - type: web
    name: glitzmia-backend
    env: node
    rootDir: BACKEND
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      # Add these in Render dashboard or here if you prefer committing (not recommended for secrets)
      # - key: MONGODB_URI
      #   sync: false
      # - key: RAZORPAY_KEY_ID
      #   sync: false
      # - key: RAZORPAY_KEY_SECRET
      #   sync: false

